CREATE DATABASE DEMO
GO
USE DEMO
GO

CREATE TABLE tbl_KHOA
(
	MaKhoa VARCHAR(8) CONSTRAINT PK_KHOA PRIMARY KEY,
	TenKhoa NVARCHAR(30)
)
GO

INSERT INTO dbo.tbl_KHOA
(
    MaKhoa,
    TenKhoa
)
VALUES
	('CNTT', N'Công nghệ thông tin'),
	('TAMLY', N'Tâm lý')
GO


CREATE TABLE tbl_USER
(
	MaNV VARCHAR(8) CONSTRAINT PK_USER PRIMARY KEY,
	TenNV NVARCHAR(52),
	Email VARCHAR(20),
	SDT VARCHAR(11),
	ChucVu INT,
	MaKhoa VARCHAR(8),
	TenDN VARCHAR(16),
	MatKhau VARBINARY(MAX) NOT NULL,
	PubKey VARCHAR(50),
	PriKey VARCHAR(50)
)
GO

CREATE TABLE tbl_SINHVIEN
(
	MaSV VARCHAR(10) CONSTRAINT PK_SINHVIEN PRIMARY KEY,
	TenSV NVARCHAR(52)
)
GO

INSERT INTO dbo.tbl_SINHVIEN
(
    MaSV,
    TenSV
)
VALUES
	('4301123123', N'Nguyễn Văn A'),
	('4301456456', N'Trần Thị B')
GO


CREATE TABLE tbl_LOPHP
(
	MaNV VARCHAR(8),
	MaLop VARCHAR(12) CONSTRAINT PK_LOPHP PRIMARY KEY,
	TenLop NVARCHAR(50)
)
GO

INSERT INTO dbo.tbl_LOPHP
(
    MaNV,
    MaLop,
    TenLop
)
VALUES
	('GV01', 'MATH101', N'Toán cao cấp 1'),
	('GV01', 'MATH201', N'Toán cao cấp 2'),
	('GV02','MILI101', N'Quốc phòng 1')
GO

CREATE TABLE tbl_BANGDIEM
(
	MaLop VARCHAR(12),
	MaSV VARCHAR(10),
	Diem VARBINARY(MAX),
	CONSTRAINT PK_BANGDIEM PRIMARY KEY(MaLop, MaSV),	
)
GO

INSERT INTO dbo.tbl_BANGDIEM
(
    MaLop,
    MaSV,
    Diem
)
VALUES
	('MATH101','4301123123',8.0),
	('MILI101','4301123123',9.0)
GO


ALTER TABLE dbo.tbl_LOPHP ADD CONSTRAINT FK_LOPHP_USER_MaNV FOREIGN KEY (MaNV) REFERENCES dbo.tbl_USER (MaNV)
ALTER TABLE dbo.tbl_BANGDIEM ADD CONSTRAINT FK_BANGDIEM_SINHVIEN FOREIGN KEY (MaSV) REFERENCES dbo.tbl_SINHVIEN (MaSV)
ALTER TABLE dbo.tbl_BANGDIEM ADD CONSTRAINT FK_BANGDIEM_LOPHP FOREIGN KEY (MaLop) REFERENCES dbo.tbl_LOPHP (MaLop)
ALTER TABLE dbo.tbl_USER ADD  CONSTRAINT FK_USER_KHOA_MaKhoa FOREIGN KEY (MaKhoa) REFERENCES dbo.tbl_KHOA (MaKhoa)

