CREATE DATABASE DEMO
GO
USE DEMO
GO

CREATE TABLE tbl_KHOA
(
	MaKhoa VARCHAR(8) CONSTRAINT PK_KHOA PRIMARY KEY,
	TenKhoa NVARCHAR(30)
)
GO

INSERT INTO dbo.tbl_KHOA
(
    MaKhoa,
    TenKhoa
)
VALUES
	('CNTT', N'Công nghệ thông tin'),
	('TAMLY', N'Tâm lý')
GO


CREATE TABLE tbl_USER
(
	MaNV INT IDENTITY (1001,1) CONSTRAINT PK_USER PRIMARY KEY,
	TenNV NVARCHAR(52),
	Email VARCHAR(20),
	SDT VARCHAR(11),
	ChucVu INT, --0 là admin, 1 là giáo viên, 2 là giáo vụ
	MaKhoa VARCHAR(8),
	TenDN VARCHAR(16),
	MatKhau VARBINARY(MAX) NOT NULL,
	PubKey VARCHAR(50),
	PriKey VARCHAR(50)
)
GO

CREATE TABLE tbl_SINHVIEN
(
	MaSV VARCHAR(10) CONSTRAINT PK_SINHVIEN PRIMARY KEY,
	TenSV NVARCHAR(52)
)
GO

INSERT INTO dbo.tbl_SINHVIEN
(
    MaSV,
    TenSV
)
VALUES
	('4301123123', N'Nguyễn Văn A'),
	('4301456456', N'Trần Thị B')
GO


CREATE TABLE tbl_LOPHP
(
	MaNV INT,
	MaLop VARCHAR(12) CONSTRAINT PK_LOPHP PRIMARY KEY,
	TenLop NVARCHAR(50)
)
GO

INSERT INTO dbo.tbl_LOPHP
(
    MaNV,
    MaLop,
    TenLop
)
VALUES
	('1002', 'MATH101', N'Toán cao cấp 1'),
	('1002', 'MATH201', N'Toán cao cấp 2'),
	('1003','MILI101', N'Quốc phòng 1')
GO

CREATE TABLE tbl_BANGDIEM
(
	MaLop VARCHAR(12),
	MaSV VARCHAR(10),
	Diem VARBINARY(MAX),
	CONSTRAINT PK_BANGDIEM PRIMARY KEY(MaLop, MaSV),	
)
GO

INSERT INTO dbo.tbl_BANGDIEM
(
    MaLop,
    MaSV,
    Diem
)
VALUES
	('MATH101','4301123123',8.0),
	('MILI101','4301123123',9.0)
GO


ALTER TABLE dbo.tbl_LOPHP ADD CONSTRAINT FK_LOPHP_USER_MaNV FOREIGN KEY (MaNV) REFERENCES dbo.tbl_USER (MaNV)
ALTER TABLE dbo.tbl_BANGDIEM ADD CONSTRAINT FK_BANGDIEM_SINHVIEN FOREIGN KEY (MaSV) REFERENCES dbo.tbl_SINHVIEN (MaSV)
ALTER TABLE dbo.tbl_BANGDIEM ADD CONSTRAINT FK_BANGDIEM_LOPHP FOREIGN KEY (MaLop) REFERENCES dbo.tbl_LOPHP (MaLop)
ALTER TABLE dbo.tbl_USER ADD  CONSTRAINT FK_USER_KHOA_MaKhoa FOREIGN KEY (MaKhoa) REFERENCES dbo.tbl_KHOA (MaKhoa)

INSERT INTO dbo.tbl_USER
(
    TenNV,
    Email,
    SDT,
    ChucVu,
    MaKhoa,
	TenDN,
	MatKhau,
    PubKey,
    PriKey
)
VALUES
(
    N'Administrator', -- TenNV - nvarchar(52)
    NULL,  -- Email - varchar(20)
    NULL,  -- SDT - varchar(11)
    0,   -- ChucVu - int
    (SELECT MaKhoa FROM dbo.tbl_KHOA WHERE dbo.tbl_KHOA.MaKhoa = 'CNTT'),  -- MaKhoa - varchar(8)
    'admin',
	CONVERT(VARBINARY(max),N'0xE99A18C428CB38D5F260853678922E03',1),
	NULL,  -- PubKey - varchar(50)
    NULL  -- PriKey - varchar(50)
    )
